### PR TITLE
Add support for mmdebstrap's --extract-hook option

### PR DESCRIPTION
**Pull request by jaxvanyang**
This is a tiny update. I only edit the `bdebstrap` script to support `--extract-hook`, and the `test_config.py` to make it pass unit test. `bdebstrap.1.md` looks like generated, I didn't find a way to generate it, so I didn't touch it (please let me know how if it is). I don't know if extra test needed, it works file for my use case. (I'm not familiar with Python testing, sorry)

### CODE REVIEW

**Comment by bdrung** [comment]
Thanks for the patch. It looks correct from a quick view. `bdebstrap.1.md` is hand-written and used as base for generating the man page. Can you add the documentation to `bdebstrap.1.md`?

**Comment by jaxvanyang** [comment]
Force pushed the change, also fix the order of `add_argument()` to match the execution order of hooks. FYI, one of my use case is to use `bdebstrap` to make cross build sysroot. I only need the libraries, so I use the extract variant and the chrootless mode. That's why I need extract hooks. I use it to fix broken absolute symbolic links, maybe it's a good example for tesing. What do think? BTW, I need to sleep now, thanks for quick response ;)

**Comment by jaxvanyang** [comment]
Added a simple test in this force push, and fixed a bug (ordering & list sanitization, nice CI!) according the result. The only failed check seems acceptable, as other lines aroud that problem line also lack coverage.

**Comment by jaxvanyang** [comment]
@bdrung can we merge now?

**Comment by jaxvanyang** [comment]
Understand, people are always busy at the end of the year. Can you release a new version and push it to package registries after merging? Although I already use my patched version at work.

**Comment by bdrung** [comment]
I'll checked the mmdebstrap changes in the last years and bdebstrap is missing support for `--hook-dir`. That support needs to be added before cutting the next release. Patches are welcome.

**Comment by jaxvanyang** [comment]
> I'll checked the mmdebstrap changes in the last years and bdebstrap is missing support for `--hook-dir`. That support needs to be added before cutting the next release. Patches are welcome.

I respect your rigour. I would like to do this patch, but I think you can do it better and faster. So maybe you should do it by yourself ;)

**Comment by bdrung** [comment]
bdebstrap 0.6.0 is released.

**Comment by jaxvanyang** [comment]
Cheers, I have also updated the package on [AUR](https://aur.archlinux.org/packages/bdebstrap).

**Comment by bdrung** [comment]
Thanks. It's nice to see the project used and even packaged for other Linux distributions.

**Pull request merged**
